### Input
# input rgba image path (default to None, can be load in GUI too)
input: 
# input text prompt (default to None, can be input in GUI too)
prompt:
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh:
# estimated elevation angle for input image 
elevation: 0
# reference image resolution
ref_size: 256
# density thresh for mesh extraction
density_thresh: 0.5

### Output
outdir: logs
mesh_format: frames
save_path: ''
save_model: False

### Training
# guidance loss weights (0 to disable)
mvdream: False
imagedream: False
lambda_sd: 0
lambda_zero123: 1
# use stable-zero123 instead of zero123-xl
stable_zero123: True 
lambda_svd: 0
# training batch size per iter
batch_size: 14
# training iterations for stage 1
iters: 500
# training iterations for stage 2
iters_refine: 50
# training camera radius
radius: 1.5
# training camera fovy
fovy: 49.1 # align with zero123 rendering setting (ref: https://github.com/cvlab-columbia/zero123/blob/main/objaverse-rendering/scripts/blender_script.py#L61
# training camera min elevation
min_ver: -30
# training camera max elevation
max_ver: 30
# checkpoint to load for stage 1 (should be a ply file)
load:
# whether allow geom training in stage 2
train_geo: False
# prob to invert background color during training (0 = always black, 1 = always white)
invert_bg_prob: 0.
n_views: 1
t_max: 0.5


### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 800
W: 800

### Gaussian splatting
optimize_gaussians: True
position_lr_init: 0.001
position_lr_final: 0.00002
position_lr_delay_mult: 0.02
position_lr_max_steps: 500
feature_lr: 0.01
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.005

num_pts: 5000
sh_degree: 0
percent_dense: 0.1
density_start_iter: 3000
density_end_iter: 3000
densification_interval: 100
opacity_reset_interval: 700
densify_grad_threshold: 0.05

# deformation field
deformation_lr_init: 0.00064
deformation_lr_final: 0.00064
deformation_lr_delay_mult: 0.01
grid_lr_init: 0.0064
grid_lr_final: 0.0064

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2

deformation:
    net_width: 64
    timebase_pe: 4
    defor_depth: 1
    posebase_pe: 10
    scale_rotation_pe: 2
    opacity_pe: 2
    timenet_width: 64
    timenet_output: 32
    bounds: 1.6
    plane_tv_weight: 0.0001
    time_smoothness_weight: 0.01
    l1_time_planes: 0.0001
    kplanes_config:
        grid_dimensions: 2
        input_coordinate_dim: 4
        output_coordinate_dim: 32
        resolution: [32, 32, 32, 22]
    multires: [1]
    no_grid: False
    no_mlp: False
    no_ds: False
    no_dr: False
    no_do: True
    use_res: True

data_mode: svd
downsample_rate: 1
# data_mode: c4d
# downsample_rate: 2